name: Create a release candidate branch

on:
  workflow_dispatch:

jobs:
  create-release-candidate:
jobs:
  try-to-fail:
    strategy:
      matrix:
        version: [16, 18, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: yarn
      - run: yarn tryToCrash
