name: Try to fail

on:
  workflow_dispatch:

jobs:
  try-to-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: nvm install && nvm use && node --version
      - run: yarn
      - run: yarn tryToCrash
